## Math fun 
- eska use krke app Array me add subtract and Multi dive Kar skte h 

In [1]:
from numpy import*


In [2]:
a = array([101,102,103,104,105,106])

In [3]:
print(a)

[101 102 103 104 105 106]


In [8]:
# Everay ele in array ko one one by one access krega
a = a+11
a

array([123, 124, 125, 126, 127, 128])

In [9]:
b = array([112, 113, 114, 115, 116, 117])


In [10]:
c = a+b
c

array([235, 237, 239, 241, 243, 245])

In [11]:
for ele in range(len(a)):
    print(a[ele])

123
124
125
126
127
128
