In [1]:
from numpy import*

## Slicing Hamari range(group) of Value ko print krbati h 

In [2]:
a = array([[2,23,34],
          [34,35,565]])
a

array([[  2,  23,  34],
       [ 34,  35, 565]])

In [6]:
print("Oth Row In")
s = a[0,:] #Phla bala hamar Row ke kam krtah , column ke liye kam krta : sabhi ko pich kar
print(s)

Oth Row In
[ 2 23 34]


In [7]:
s = a[:,0]
print(s)

[ 2 34]


## print the specific value

In [9]:
s = a[0:1,0:1]
print(s)

[[2]]


In [10]:
s = a[1:2,2:3]
print(s)

[[565]]


## Range me Value access krna

In [11]:
s = a[0:2,1:3]
print(s)

[[ 23  34]
 [ 35 565]]
